name: "Harden Runner"
description: "GitHub Actions Runtime Security"
inputs:
  allowed-endpoints:
    description: "Only these endpoints will be allowed if egress-policy is set to block"
    required: false
    default: ""
  egress-policy:
    description: "Policy for outbound traffic, can be either audit or block"
    required: false
    default: "block"
  disable-sudo:
    description: "Disable sudo access for the runner account"
    required: false
    default: "false"
  disable-file-monitoring:
    description: "Disable file monitoring"
    required: false
    default: "false"
branding:
  icon: "check-square"
  color: "green"
runs:
  using: "node12"
  pre: "dist/pre/index.js"
  main: "dist/index.js"
  post: "dist/post/index.js"
